name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "RoomCull v${{ steps.get_version.outputs.VERSION }}"
        body: |
          ## RoomCull v${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          1. Download the JAR file below
          2. Install NeoForge for Minecraft 1.21.1
          3. Place the JAR in your `mods` folder
          4. Launch Minecraft
          
          ### What's New
          - Room-based occlusion culling for improved performance
          - Automatic room boundary detection
          - Visual debug particles showing room bounds
          - Glowstone-textured room blocks
          
          ### Requirements
          - Minecraft 1.21.1
          - NeoForge 21.0.167+
        files: |
          build/libs/*.jar
        draft: false
        prerelease: false